"""init

Revision ID: 217765c3391e
Revises: 
Create Date: 2023-08-10 22:22:04.048310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217765c3391e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=False),
    sa.Column('study_level', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('coc', sa.Boolean(), nullable=True),
    sa.Column('share_registration', sa.Boolean(), nullable=True),
    sa.Column('send_emails', sa.Boolean(), nullable=True),
    sa.Column('underrepresented', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('sexual_identity', sa.String(), nullable=False),
    sa.Column('shirt_size', sa.String(), nullable=False),
    sa.Column('address_line_1', sa.String(), nullable=False),
    sa.Column('address_line_2', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dietary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signup_id', sa.Integer(), nullable=True),
    sa.Column('vegetarian', sa.Boolean(), nullable=True),
    sa.Column('vegan', sa.Boolean(), nullable=True),
    sa.Column('celiac', sa.Boolean(), nullable=True),
    sa.Column('allergies', sa.Boolean(), nullable=True),
    sa.Column('allergies_explained', sa.String(), nullable=True),
    sa.Column('kosher', sa.Boolean(), nullable=True),
    sa.Column('halal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(('signup_id',), ['signup.id'],)
    )
    op.create_table('pronouns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signup_id', sa.Integer(), nullable=True),
    sa.Column('she_her', sa.Boolean(), nullable=True),
    sa.Column('he_him', sa.Boolean(), nullable=True),
    sa.Column('they_them', sa.Boolean(), nullable=True),
    sa.Column('other', sa.String(), nullable=True),
    sa.Column('prefer_not_to_answer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(('signup_id',), ['signup.id'],)
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signup_id', sa.Integer(), nullable=True),
    sa.Column('asian_indian', sa.Boolean(), nullable=True),
    sa.Column('black_african', sa.Boolean(), nullable=True),
    sa.Column('chinese', sa.Boolean(), nullable=True),
    sa.Column('filipino', sa.Boolean(), nullable=True),
    sa.Column('guamanian_chamorro', sa.Boolean(), nullable=True),
    sa.Column('hispanic_latino_spanish', sa.Boolean(), nullable=True),
    sa.Column('japanese', sa.Boolean(), nullable=True),
    sa.Column('korean', sa.Boolean(), nullable=True),
    sa.Column('middle_eastern', sa.Boolean(), nullable=True),
    sa.Column('native_american_alaskan', sa.Boolean(), nullable=True),
    sa.Column('native_hawaiian', sa.Boolean(), nullable=True),
    sa.Column('samoan', sa.Boolean(), nullable=True),
    sa.Column('vietnamese', sa.Boolean(), nullable=True),
    sa.Column('white', sa.Boolean(), nullable=True),
    sa.Column('other_asian', sa.Boolean(), nullable=True),
    sa.Column('other_pacific_island', sa.Boolean(), nullable=True),
    sa.Column('other', sa.String(), nullable=True),
    sa.Column('prefer_not_to_answer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(('signup_id',), ['signup.id'],)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race')
    op.drop_table('pronouns')
    op.drop_table('dietary')
    op.drop_table('signup')
    # ### end Alembic commands ###
